version: '2'
services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=terradonuncadb
      - POSTGRES_USER=terradonuncadb
      - POSTGRES_PASSWORD=terradonuncadb
      - MAX_CONNECTIONS=terradonuncadb
    volumes:
      - ./tables.sql:/docker-entrypoint-initdb.d/setup.sql

